name: Build Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-android:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 7
          submodules: recursive
      - uses: actions/setup-java@v1
        with:
          java-version: '21'
      - name: "npm install"
        run: |
          npm ci
      - name: "patch deps"
        run: |
          node ./ci/patch-deps
      - name: "build jsbundle"
        run: |
          npm run bundle-rnjs
      - name: "Setup variables"
        id: build-config
        run: |
          echo 'is_prerelease='$(node ./ci/is-prerelease "$(basename ${{ github.ref }})") >> $GITHUB_OUTPUT
          echo 'version_name='$(basename ${{ github.ref }} | sed 's/^v//') >> $GITHUB_OUTPUT
      - name: "Build for Google Play"
        run: |
          [[ -z "${{ steps.build-config.outputs.version_name }}" ]] && exit 13
          npm run play -- --no-daemon
      - name: "Build for Github release"
        run: |
          [[ -z "${{ steps.build-config.outputs.version_name }}" ]] && exit 13
          USE_SPLITBUILD=1 CI_BUILD=1 CI_VERSION_NAME="${{ steps.build-config.outputs.version_name }}" ./gradlew assembleRelease --no-daemon
      - name: "Changelog"
        run: |
           git log -p -n1 -- CHANGELOG.md  | grep -Po '(?<=^\+)(?!\+\+).*' > CHANGELOG_current.md
      - name: Upload GitHub Actions artifact of vcpkg build
        uses: actions/upload-artifact@v4
        name: Build Android CI
        path: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk